from pydantic import BaseModel, ConfigDict, Field

from storyos.artifacts.base import BaseArtifact


class Specialist(BaseModel):
    """
    Optional review specialist inserted into the review gate.
    """

    model_config = ConfigDict(
        strict=True,
        frozen=True,
        extra="forbid",
    )

    name: str = Field(
        description="Specialist name.",
    )

    enabled: bool = Field(
        description="Whether the specialist is active.",
    )

    objective: str = Field(
        description="Responsibility of the specialist.",
    )


class Plan(BaseArtifact):
    """
    Execution plan generated by the Planner Agent.

    The Orchestrator follows this plan for the entire run.
    """

    outline_template: str = Field(
        description="Outline strategy to use.",
    )

    critic_rubric: str = Field(
        description="Critic evaluation rubric.",
    )

    specialists: list[Specialist] = Field(
        default_factory=list,
        description="Additional review specialists.",
    )

    revision_budget: int = Field(
        ge=0,
        description=(
            "Maximum number of Draft revision iterations "
            "for the entire review cycle. "
            "This budget is shared across all review agents."
        )
    )

    artifact_type: str = "plan"
